name: learning_flutter_base
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.11.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # 日本語化用
  flutter_localizations:
    sdk: flutter
  # Firebase用
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.0
  cloud_functions: ^5.5.0
  # 以前から使っていたもの
  url_launcher: ^6.1.0
  cupertino_icons: ^1.0.8
  # お客様情報保存用
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

# 💡 ここから下が flutter: のブロックです。重複をなくし、すっきりまとめました。
flutter:
  uses-material-design: true

  assets:
    - assets/images/notice_yomogi.jpg
