// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIBLsEnh6ol26_cXKS41ztDo1S4v71uxk',
    appId: '1:507730376251:web:37ca13af388676651d0e1e',
    messagingSenderId: '507730376251',
    projectId: 'comehiro-app-439f7',
    authDomain: 'comehiro-app-439f7.firebaseapp.com',
    storageBucket: 'comehiro-app-439f7.firebasestorage.app',
    measurementId: 'G-9ET1TQWRCZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZLt4Q0RJ-vumsSVz4A4I5pmpKsQ3dho',
    appId: '1:507730376251:android:85a675ac810e85431d0e1e',
    messagingSenderId: '507730376251',
    projectId: 'comehiro-app-439f7',
    storageBucket: 'comehiro-app-439f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi7FrCqGt1qIy1sIS-cumIY0dQZ_xO1yw',
    appId: '1:507730376251:ios:ebbe1172e69d03441d0e1e',
    messagingSenderId: '507730376251',
    projectId: 'comehiro-app-439f7',
    storageBucket: 'comehiro-app-439f7.firebasestorage.app',
    iosBundleId: 'com.example.learningFlutterBase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi7FrCqGt1qIy1sIS-cumIY0dQZ_xO1yw',
    appId: '1:507730376251:ios:ebbe1172e69d03441d0e1e',
    messagingSenderId: '507730376251',
    projectId: 'comehiro-app-439f7',
    storageBucket: 'comehiro-app-439f7.firebasestorage.app',
    iosBundleId: 'com.example.learningFlutterBase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIBLsEnh6ol26_cXKS41ztDo1S4v71uxk',
    appId: '1:507730376251:web:4a1c70eedee3aa791d0e1e',
    messagingSenderId: '507730376251',
    projectId: 'comehiro-app-439f7',
    authDomain: 'comehiro-app-439f7.firebaseapp.com',
    storageBucket: 'comehiro-app-439f7.firebasestorage.app',
    measurementId: 'G-6S0GH7Z6RT',
  );

}